apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: pbl-security
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        tier: api
    spec:
      containers:
        - name: backend
          image: busybox:1.36.1
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - mkdir -p /www; echo backend > /www/index.html; exec httpd -f -p 80 -h /www
          ports:
            - containerPort: 80
          env:
            - name: UPSTREAM_SERVICE
              value: http://db.pbl-security.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: pbl-security
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 80
      targetPort: 80
